openapi: 3.1.0
info:
  version: 0.2.133
  title: Hail Services
  # termsOfService: TBC
  contact:
    name: Contact our support
    email: hail-team@broadinstitute.org
    url: https://www.hail.is/gethelp.html
  license:
    name: MIT Licence
    url: https://github.com/hail-is/hail/blob/main/LICENSE
  x-logo:
    url: 'https://hail.is/static/hail-logo-cropped-sm-opt.png'
    altText: Hail logo
  description: >
    Hail is a ....
    These services are for ....
externalDocs:
  description: "Find out how to create a GitHub repo for your OpenAPI definition."
  url: 'https://github.com/Redocly/create-openapi-repo'
tags:
  - name: Public
    description: "Operations for retrieving basic public information from the service."
  - name: Authenticated Information
    description: "Operations for retrieving information that require authentication."
x-tagGroups:
  - name: General
    tags:
      - 'Public'
      - 'Authenticated Information'
#  - name: Administration
#    tags:
#      - Admin
servers:
  - url: {{ base_url }}
    description: "Current Batch service. No risk of CORS issues."
  - url: https://batch.hail.is/
    description: "GCP Production Batch service. Beware CORS issues in swagger / browsers."
  - url: https://batch.azure.hail.is/
    description: "Azure Production Batch service. Beware CORS issues in swagger / browsers."
  - url: https://internal.hail.is/{devname}/batch/
    description: "Developer Batch service. Beware CORS issues in swagger / browsers."
    variables:
      devname:
        description: Developer environment name
paths:
  '/api/v1alpha/version':
    get:
      summary: "Version"
      description: "Get the version of the API."
      operationId: getVersion
      tags:
        - Public
      responses:
        '200':
          description: "Successfully retrieved the version of the API."
          content:
            string:
              example: "0.2.133"
  '/healthcheck':
    get:
      summary: "Healthcheck"
      description: "Check the health of the API."
      operationId: healthcheck
      tags:
        - Public
      responses:
        '200':
          description: "Successfully checked the health of the API."
  '/api/v1alpha/cloud':
    get:
      summary: "Cloud"
      description: "Get the cloud provider supported by this batch instance."
      operationId: getCloudProvider
      tags:
        - Public
      responses:
        '200':
          description: "Successfully retrieved the cloud provider supported."
          content:
            string:
              example: "gcp"
  '/api/v1alpha/supported_regions':
    get:
      summary: "Supported Regions"
      description: "Get the list of supported regions."
      operationId: getSupportedRegions
      tags:
        - Authenticated Information
      responses:
        '200':
          description: "Successfully retrieved the regions list."
          content:
            string:
              example: "TODO"

components:
  securitySchemes:
    main_auth:
      description: "GCP production hail login (hail.is and internal.hail.is)"
      type: oauth2
      flows:
        implicit:
          authorizationUrl: {{ auth_base_url }}/login
#          clientId: '842871226259-4oshjtt0j9n88k4j8a601gsv64mc7eql.apps.googleusercontent.com'
          redirectUrl: {{ base_url }}/swagger
#          scopes:
#            'read:users': read user info
#            'write:users': modify or remove users
    api_key:
      description: "Use a token from another oauth login session. Not recommended!"
      type: apiKey
      in: header
      name: Authorization
#    basic_auth:
#      type: http
#      scheme: basic
#webhooks:
#  # TODO: Github -> CI webhooks?
#  userInfo:
#    post:
#      summary: New user webhook
#      description: "Information about a new user in the system."
#      operationId: userInfo
#      tags:
#        - Info
#      requestBody:
#        content:
#          application/json:
#            schema:
#              $ref: 'components/schemas/User.yaml'
#      responses:
#        '200':
#          description: "Successfully retrieved information about a new user."
#      security:
#        - api_key: []
