name: AppSec Approval Check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-appsec-approval:
    name: Check AppSec Team Approval
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get all history for changed files check

      - name: Generate installation token
        id: generate-token
        run: |
          # Install jwt-cli for JWT generation
          sudo apt-get update && sudo apt-get install -y jwt-cli

          # Generate JWT with required claims
          JWT=$(echo "${{ secrets.APPSEC_REVIEW_APP_PRIVATE_KEY }}" | jwt encode \
            --alg RS256 \
            --kid "" \
            --iss "${{ secrets.APPSEC_REVIEW_APP_APP_ID }}" \
            --exp $(( $(date +%s) + 600 )) \
            --iat $(date +%s) \
            -)

          # Get installation token using stored installation ID
          TOKEN=$(curl -s -X POST \
            -H "Authorization: Bearer $JWT" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/app/installations/${{ secrets.APPSEC_REVIEW_APP_INSTALLATION_ID }}/access_tokens" | jq -r '.token')

          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Check for changes in sensitive directories
        id: check-changes
        run: |
          # Get the base branch (usually main/master)
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          HEAD_SHA=${{ github.event.pull_request.head.sha }}
          
          # Check for changes in specified directories
          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)
          SENSITIVE_CHANGES=false
          
          # List of sensitive directories to check
          SENSITIVE_DIRS=(
            ".github/"
            "batch/"
            "ci/"
            "auth/"
            "gear/"
            "gateway/"
            "grafana/"
            "guide/"
            "infra/"
            "internal-gateway/"
            "letsencrypt/"
            "monitoring/"
            "prometheus/"
            "tls/"
            "ukbb-rg/"
            "web_common/"
            "website/"
          )
          
          for FILE in $CHANGED_FILES; do
            for DIR in "${SENSITIVE_DIRS[@]}"; do
              if [[ $FILE == $DIR* ]]; then
                SENSITIVE_CHANGES=true
                echo "Found changes in sensitive directory: $DIR"
                break 2
              fi
            done
          done
          
          echo "sensitive-changes=$SENSITIVE_CHANGES" >> $GITHUB_OUTPUT

      - name: Request AppSec team review if needed
        if: steps.check-changes.outputs.sensitive-changes == 'true'
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        id: request-review
        run: |
          # Check if review was already requested
          REQUESTED_REVIEWERS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers)
          
          # Check if appsec team is already requested
          TEAM_ALREADY_REQUESTED=$(echo "$REQUESTED_REVIEWERS" | jq -r '.teams[] | select(.slug=="appsec") | .slug')
          
          if [ -z "$TEAM_ALREADY_REQUESTED" ]; then
            echo "Requesting review from AppSec team..."
            gh pr edit ${{ github.event.pull_request.number }} --add-reviewer "hail-is/appsec"
          else
            echo "Review from AppSec team already requested"
          fi

      - name: Check AppSec team approval
        if: steps.check-changes.outputs.sensitive-changes == 'true'
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        id: check-approval
        run: |
          # Get the PR reviews
          REVIEWS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews)
          
          # Check if any member of the appsec team has approved
          APPROVED=false
          
          # Get the list of members in the appsec team
          TEAM_MEMBERS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/hail-is/teams/appsec/members | jq -r '.[].login')
          
          # Check if any team member has approved
          echo "$REVIEWS" | jq -r '.[] | select(.state=="APPROVED") | .user.login' | while read REVIEWER; do
            if echo "$TEAM_MEMBERS" | grep -q "^${REVIEWER}$"; then
              APPROVED=true
              echo "Found approval from AppSec team member: $REVIEWER"
              break
            fi
          done
          
          if [ "$APPROVED" = "true" ]; then
            echo "AppSec team approval found"
            exit 0
          else
            echo "No AppSec team approval found yet"
            exit 1
          fi

      - name: Set status
        if: steps.check-changes.outputs.sensitive-changes == 'true' && failure()
        run: |
          echo "Changes in sensitive directories require approval from the AppSec team"
          exit 1 
